# Generated by Django 4.2.18 on 2025-01-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postform_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
