# Generated by Django 4.2.18 on 2025-02-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
